### PR TITLE
Create pt_br.json + recipe and tags tweaks

### PR DESCRIPTION
**Pull request by Brun333rp**
Brazilian Portuguese translations, and recipe/tag related stuff

### CODE REVIEW

**Comment by Brun333rp** [comment]
well, I bet everything is done

**Comment by BlueDuckYT** [comment]
Thanks for the help!

**Comment by Brun333rp** [comment]
no problem!

**Comment by Brun333rp** [comment]
weird, for some reason many of the compatibility recipes I uploaded weren't merged ... is that a bug from github?

**Pull request merged**
